# Generated by Django 3.2.8 on 2021-11-02 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0004_business'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='business_name',
            new_name='name',
        ),
    ]
