# Generated by Django 3.2.8 on 2021-11-02 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0006_business_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='business_email',
            new_name='email',
        ),
    ]
